//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class audiDeportivoEntities1 : DbContext
    {
        public audiDeportivoEntities1()
            : base("name=audiDeportivoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<serie3> serie3 { get; set; }
        public virtual DbSet<serie5> serie5 { get; set; }
        public virtual DbSet<serie7> serie7 { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
