//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie3
    {
        public short id_coche { get; set; }
        public string nombre { get; set; }
        public string modelo { get; set; }
        public short cv { get; set; }
        public string consumo { get; set; }
        public byte[] imagen { get; set; }
    }
}
