//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public short id_user { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string tipoUsuario { get; set; }
        public string email { get; set; }
        public string pass { get; set; }
    }
}
